Countdown:
  messageInterval: 2000
  legacyFile: ksc.json
  KSC:
    host: countdown.ksc.nasa.gov
    port: 11142
  VAFB:
    host: countdown.ksc.nasa.gov
    port: 11144
Server:
  port: 8080
  webSocketPath: /ws
